apiVersion: v1
kind: Pod
metadata:
  name: fsc
  labels:
    app: jataware
spec:
  volumes:
    - name: results
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
  - name: fsc-jataware
    image: jataware/fsc_model:0.1
    args: ["0", "1", "0.5"]
    ports:
      - containerPort: 80
        name: "http-server"
    volumeMounts:
      - name: results
        mountPath: /outputs
    name: task-pv-storage
  restartPolicy: Never